// Generated by CoffeeScript 1.9.2
(function() {
  var DocumentDBMock, generateData, mock, rewire;

  rewire = require("rewire");

  generateData = rewire('../stored-procedures/createVariedDocuments');

  DocumentDBMock = require('../DocumentDBMock');

  mock = new DocumentDBMock(generateData);

  exports.generateDataTest = {
    basicTest: function(test) {
      var i, key, len, memo, ref;
      memo = generateData.generateData({
        remaining: 3
      });
      test.deepEqual(memo, {
        remaining: 0,
        totalCount: 3,
        countForThisRun: 3
      });
      test.equal(mock.rows.length, 3);
      ref = ['ProjectHierarchy', 'Priority', 'Severity', 'Points', 'State'];
      for (i = 0, len = ref.length; i < len; i++) {
        key = ref[i];
        test.ok(mock.lastRow.hasOwnProperty(key));
      }
      return test.done();
    },
    throwTest: function(test) {
      var f;
      f = function() {
        var memo;
        return memo = generateData.generateData();
      };
      test.throws(f);
      return test.done();
    },
    testTimeout: function(test) {
      var memo;
      mock.collectionOperationQueuedList = [true, false, false];
      memo = generateData.generateData({
        remaining: 3
      });
      test.equal(memo.remaining, 2);
      test.equal(memo.totalCount, 1);
      test.equal(memo.countForThisRun, 1);
      mock.collectionOperationQueuedList = [true, true, true];
      memo = generateData.generateData(memo);
      test.equal(memo.remaining, 0);
      test.equal(memo.totalCount, 3);
      test.equal(memo.countForThisRun, 2);
      return test.done();
    }
  };

}).call(this);

//# sourceMappingURL=testCreateVariedDocuments.js.map
